import turtle
kelly = turtle.Turtle()
ellie = turtle.Turtle()
vanessa = turtle.Turtle()
mary = turtle.Turtle()
hope = turtle.Turtle()
joy = turtle.Turtle()
kelly.speed(30)
ellie.speed(30)
vanessa.speed(30)
mary.speed(30)
hope.speed(30)
joy.speed(30)
ellie.pensize(7)
vanessa.pensize(7)
mary.pensize(7)
scn = turtle.Screen()

kelly.penup()
kelly.goto(0,-150)
kelly.begin_fill()
kelly.color("yellow")
kelly.pendown()
kelly.circle(200)
kelly.end_fill()

ellie.penup()
ellie.goto(90,80)
ellie.pendown()
ellie.left(90)
ellie.circle(30,180)

vanessa.penup()
vanessa.goto(-40,80)
vanessa.pendown()
vanessa.left(90)
vanessa.circle(30,180)

mary.penup()
mary.goto(-120,0)
mary.pendown()
mary.right(60)
mary.circle(140,120)

hope.penup()
hope.goto(140,10)
hope.begin_fill()
hope.color("salmon")
hope.pendown()
hope.circle(40)
hope.end_fill()

joy.penup()
joy.goto(-140,10)
joy.begin_fill()
joy.color("salmon")
joy.pendown()
joy.circle(40)
joy.end_fill()

kelly.penup()
kelly.goto(180,180)
ellie.penup()
ellie.goto(180,180)
vanessa.penup()
vanessa.goto(180,180)
mary.penup()
mary.goto(180,180)
hope.penup()
hope.goto(180,180)
joy.penup()
joy.goto(180,180)
kelly.color("white")
ellie.color("white")
vanessa.color("white")
mary.color("white")
hope.color("white")
joy.color("white")

turtle.exitonclick()