import turtle
kelly = turtle.Turtle()
ellie = turtle.Turtle()
vanessa = turtle.Turtle()
mary = turtle.Turtle()
hope = turtle.Turtle()
joy = turtle.Turtle()
kelly.speed(50)
ellie.speed(50)
vanessa.speed(50)
mary.speed(50)
hope.speed(50)
joy.speed(50)
scn = turtle.Screen()

kelly.penup()
kelly.goto(0,-150)
kelly.begin_fill()
kelly.color("yellow")
kelly.pendown()
kelly.circle(200)
kelly.end_fill()

ellie.penup()
ellie.goto(90,80)
ellie.pendown()
ellie.left(90)
ellie.circle(30,180)

vanessa.penup()
vanessa.goto(-40,80)
vanessa.pendown()
vanessa.left(90)
vanessa.circle(30,180)

mary.penup()
mary.goto(-120,0)
mary.pendown()
mary.right(60)
mary.circle(140,120)

hope.penup()
hope.goto(140,10)
hope.begin_fill()
hope.color("salmon")
hope.pendown()
hope.circle(40)
hope.end_fill()

joy.penup()
joy.goto(-140,10)
joy.begin_fill()
joy.color("salmon")
joy.pendown()
joy.circle(40)
joy.end_fill()

turtle.exitonclick()